### ISSUE TITLE
Make the type checking work

### ISSUE THREAD

**Issue by Eomm** [nearform/the-fastify-workshop#168]
Check how to turn on the types checking works on the IDE for the serialization after setting the JSON schemas.

**Comment by Eomm** [comment]
I watched the recording to remember this issue 😂 

Here we would like to set up the types to turn on the autocompletion.
For example:

```
const { fastify } = require('fastify')

// instead of
const fastify = require('fastify')
```

this sentence turns on the autocompletion on VSCode.

It should be doable having the autocompletion for plugins as well:

```
export default async function (fastify, opts) {
  fastify. // autocompletion here
}
```

**Comment by simoneb** [comment]
Closing as wontfix. See #183 for the reason.

**Comment by simoneb** [comment]
The summary is that it's more work than it's worth. The dynamic nature of fastify plugins (e.g. decorators) doesn't make it a good fit for adding types via typedoc. If you want types, use typescript (and it will be some effort with that as well)

**Comment by RafaelGSS** [comment]
Maybe should we add the type doc for the initial examples in this repository? Just to show that it's supported -- even not to easy to implement complex types

**Comment by simoneb** [comment]
@RafaelGSS do you want to pick this up again then?
