### ISSUE TITLE
Add Typescript section

### ISSUE THREAD

**Issue by RafaelGSS** [nearform/the-fastify-workshop#170]
Section related to declaration merging and maybe `typebox` support in the validations.

**Comment by RafaelGSS** [comment]
For further reference: https://github.com/fastify/fastify/discussions/2935

**Comment by simoneb** [comment]
@RafaelGSS can you take this one? See other work I've done in #183 which may be relevant. As it stands now I've abandoned that work as some types are really tricky to get to work without using ts.
