### ISSUE TITLE
Update fastify-workshop links

### ISSUE THREAD

**Issue by tiagoheliob** [nearform/the-fastify-workshop#243]
The workshop links are referring to the old Fastify documentation.

**Comment by Eomm** [comment]
Can this issue be closed after https://github.com/nearform/the-fastify-workshop/pull/244 ?

**Comment by simoneb** [comment]
Yes. @tiagoheliob please set up https://github.com/nearform/github-action-check-linked-issues in this repo and in general remember to link issues.

**Comment by tiagoheliob** [comment]
closed by #244
