### ISSUE TITLE
use onRequest instead of preValidation in step10

### ISSUE THREAD

**Issue by mcollina** [nearform/the-fastify-workshop#28]
As titled, using onRequest is actually preferred.

**Comment by marquicodes** [comment]
Hi Matteo, would you like a PR for this? Here you mention step10, but there is similar code on steps 11 & 12.

**Comment by simoneb** [comment]
@marquicodes it would be great, yes

**Comment by toni-sharpe** [comment]
@marquicodes generally the code builds step by step so a change in step 10 would also appear in steps 11 and 12, unless one of those steps refactors it away. Be sure to change deck.md and the code examples in the folders too.

**Comment by marquicodes** [comment]
@toni-sharpe Thanks for the extra info. I will check deck.md if needs to be updated.
