### ISSUE TITLE
create an empty "work-here" folder

### ISSUE THREAD

**Issue by mcollina** [nearform/the-fastify-workshop#29]
as titled, this will direct our attendees to work there

**Comment by penx** [comment]
@mcollina were you thinking at the project root or under src?

**Comment by penx** [comment]
I'm thinking at the project root, as the work-here would have a src folder within it.

PR here https://github.com/nearform/the-fastify-workshop/pull/32

**Comment by mcollina** [comment]
> @mcollina were you thinking at the project root or under src?

src
