### ISSUE TITLE
Images are not rendering well

### ISSUE THREAD

**Issue by RafaelGSS** [nearform/the-fastify-workshop#310]
Most of the images are too small to the presentation

**Comment by simoneb** [comment]
didn't we try this out when migrating over to slidev? /cc @sameer-coder

**Comment by sameer-coder** [comment]
The images looked alright to me. The original size is not actually small. They were resized with css to fit on the screen. I think except the fastify-extensibility image others are fine. @RafaelGSS which ones do you think should be bigger?

**Comment by RafaelGSS** [comment]
We've seen it in the Matteo presentation. I have just run locally and those slides are a bit small:

![image](https://user-images.githubusercontent.com/26234614/155546714-2c9bafe5-96cd-470c-9de6-8266e17d05b2.png)

![image](https://user-images.githubusercontent.com/26234614/155546869-5e349205-6d50-43ea-bc12-0ff64fd2f4ac.png)

**Comment by simoneb** [comment]
@RafaelGSS is this still relevant?

**Comment by RafaelGSS** [comment]
> @RafaelGSS is this still relevant?

Yes, it's. Just confirmed.

**Comment by simoneb** [comment]
@castarco since you're looking into this, this is another issue on another repo using the same presentation library. I think similar issues are happening here too

**Comment by RafaelGSS** [comment]
> @castarco since you're looking into this, this is another issue on another repo using the same presentation library. I think similar issues are happening here too

Yes, definitely the images are not well managed by `slidev-theme-nearform`. I have created a PR to solve it in this presentation, but, in case you found a better way, feel free to revert/close.

**Comment by castarco** [comment]
Checking, but just in case, bear in mind that you should take into account that Slidev uses a fixed aspect ratio for the area it uses to present the contents.

Having the browser window fully maximised in a very wide screen can give an incorrect feeling of how it would be in presentation mode. Most of the blue background we can see there doesn't really belong to the slide space.

**Comment by RafaelGSS** [comment]
It was happening in Matteo Macbook as well.

> Having the browser window fully maximised in a very wide screen can give an incorrect feeling of how it would be in presentation mode.

I don't get it. The _presentation mode_ is basically what you are seeing in the image above (the last one).
