### ISSUE TITLE
Add logger config/slides and exercises

### ISSUE THREAD

**Issue by mcollina** [nearform/the-fastify-workshop#7]

**Comment by simoneb** [comment]
- you mean having a step in the workshop just about logging? 
- where do you think it would fit? do you see it as taking the code of the previous step and not changing anything apart from logging?
- what should it include to provide a good overview of logging?

**Comment by mcollina** [comment]
> you mean having a step in the workshop just about logging?

Yes, exactly. I see most people have a completely wrong setup for that

> where do you think it would fit? do you see it as taking the code of the previous step and not changing anything apart from logging?

Yes, we can add it at the end, or after we add the config

> what should it include to provide a good overview of logging?

Developer view vs Production view (pino-pretty vs json)
Multiple levels
How to configure it
Log redaction
Potentially asynchronous logging with pino.

**Comment by simoneb** [comment]
Closed by https://github.com/nearform/the-fastify-workshop/pull/22
