### ISSUE TITLE
automate the install of all dependencies in the modules in src

### ISSUE THREAD

**Issue by mcollina** [nearform/the-fastify-workshop#9]
Currently we are using a hack in CI to make test pass.

A "proper", cross-platform fix is needed so `npm test` works on windows too.

See #8 for more details.

**Comment by simoneb** [comment]
What do you think of this? https://github.com/nearform/the-fastify-workshop/pull/10/files

By using yarn workspaces we can keep all packages in the root package.json and switch to use yarn npm the step's test script so we avoid having to use npx

**Comment by simoneb** [comment]
this is addressed in master by using yarn
