### ISSUE TITLE
Database section localhost -> 0.0.0.0

### ISSUE THREAD

**Issue by Ademsk1** [nearform/the-fastify-workshop#905]
On page 74 the following postgres address is suggested 
`PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5433/postgres`
This didn't work for me, and resulted in the following error message:
```
req: {
      "method": "POST",
      "url": "/login",
      "hostname": "localhost:3000",
      ...
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED ::1:5433",
      "stack":
          Error: connect ECONNREFUSED ::1:5433
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      "errno": -61,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "::1",
      "port": 5433
    }
 ...
```
As you can see the address points to `::1`. After discussing this with @SociableSteve it appears to be that using `localhost` doesn't work in `PG_CONNECTION_STRING`. Replacing it with `0.0.0.0` resolved the issue, and would recommend this change, however, my understanding of it is limited, and so if there is a better way, please let me know.

**Comment by simoneb** [comment]
Any idea why it may be broken on your machine and running successfully in the automated tests that run in CI here in GitHub?

**Comment by Ademsk1** [comment]
Not sure to be honest but I do have a guess. The Github actions uses a Linux distro, which means that docker runs on the Linux kernel, perhaps meaning that our localhost is also the containers localhost. Macs however have to run docker inside a VM, with not connection to localhost. I am most likely wrong, but will wait from colleagues to see if they encounter the same issue...

**Comment by simoneb** [comment]
Let's do a PR to change the hostname to 0.0.0.0 and see if CI still runs
